services:
  - type: web
    name: triangle-pos
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Triangle POS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: triangle-pos-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql

databases:
  - name: triangle-pos-db
    databaseName: triangle_pos
    user: triangle_pos_user
